<?php

namespace Tests\Feature;

use Tests\TestCase;

class FeatureTestCase extends TestCase
{
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }
}
